### ISSUE TITLE
Invalid date for staking transactions

### ISSUE THREAD

**Issue by fedekunze** [cosmos/lunie#2250]
**Describe the bug**

Dates from staking transactions are updated somewhere after creation and thus the date becomes invalid.

Added a bug handler in the meantime on #2185. 

**To Reproduce**

1. Create a staking transaction
2. Go to Transactions Page (Date is OK)
3. Go to another page
4. Go once again to transactions page (Date is broken)

**Expected behavior**

Tx time shouldn't be updated

**Comment by fedekunze** [comment]
Note: This is not the case for block page's transactions

**Comment by jbibla** [comment]
i thought we addressed this with updating txs individually instead of every block?

**Comment by faboweb** [comment]
I can't reproduce this.

**Comment by faboweb** [comment]
Seems fixed on develop

**Comment by fedekunze** [comment]
No it's not (just reproduced). You need to follow the steps from above

**Comment by faboweb** [comment]
Tested on staging and I can't reproduce with the steps above.

**Comment by fedekunze** [comment]
I tested it on localhost (develop)

**Comment by faboweb** [comment]
Ok reproduced
