### ISSUE TITLE
Handle transactions included timeout

### ISSUE THREAD

**Issue by faboweb** [cosmos/lunie#2288]
**Describe the bug**

If I send a transaction and it isn't included in a block right away, we get a timeout error. But the transaction actually is already in the mempool. This is dangerous, as people might try to send the transaction again. Currently this will cause an error as the tx is in mempool. Still it is confusing.

SDK related issue: https://github.com/cosmos/cosmos-sdk/issues/3875

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
we should check the tx `log` property and check if it was successful

**Comment by faboweb** [comment]
I think if this error occurs, there is no result with a `log` property returned. Am I mistaken?
