### ISSUE TITLE
PageProposal is showing uAtoms

### ISSUE THREAD

**Issue by jbibla** [cosmos/lunie#2365]
**Describe the bug**

**To Reproduce**
- visit https://lunie.io/#/governance/2

**Expected behavior**

- PageProposal deposits, votes, and tally should be displayed in Atoms.

**Comment by fedekunze** [comment]
for me it shows `521.400000 atom`

**Comment by jbibla** [comment]
what about vote count?

**Comment by faboweb** [comment]
I think it's fine but isn't formatted country specific:

![image](https://user-images.githubusercontent.com/5869273/55003618-03b1eb00-4fd9-11e9-8896-5c0f3ffb4e0e.png)

Difference in the decimal separator

**Comment by jbibla** [comment]
that vote count can't be correct though, can it?

**Comment by faboweb** [comment]
Why not? It's waited by delegated stake
